# Generated by Django 3.1.6 on 2021-03-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0005_auto_20210321_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
