# Generated by Django 3.1.6 on 2021-03-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0004_auto_20210321_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='carts', serialize=False, to='cart.cart', verbose_name='Cart')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.IntegerField(default=375, verbose_name='Номер телефона')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.status', verbose_name='Статус заказа')),
            ],
        ),
    ]
