# Generated by Django 3.1.6 on 2021-03-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210321_1525'),
        ('order', '0005_auto_20210321_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='carts', serialize=False, to='cart.cart', unique=True, verbose_name='Cart'),
        ),
    ]
