# Generated by Django 3.1.6 on 2021-03-21 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210321_1525'),
        ('order', '0008_auto_20210321_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cart.cart', verbose_name='Cart'),
        ),
    ]
