# Generated by Django 3.1.6 on 2021-03-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210322_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус'),
        ),
    ]
