# Generated by Django 3.1.6 on 2021-03-21 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210322_0124'),
        ('order', '0011_auto_20210322_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.IntegerField(default=375, verbose_name='Номер телефона')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.cart', verbose_name='Cart')),
                ('status', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.status', verbose_name='Статус заказа')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
