# Generated by Django 3.1.6 on 2021-03-22 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210322_0124'),
        ('order', '0012_auto_20210322_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernew',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='cart.cart', verbose_name='Cart'),
        ),
    ]
