# Generated by Django 3.1.6 on 2021-03-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_ordernew_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernew',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='ordernew',
            name='coment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='ordernew',
            name='phone',
            field=models.IntegerField(default=375, null=True, verbose_name='Контактный номер телефона'),
        ),
    ]
