# Generated by Django 3.1.5 on 2021-02-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='name',
            new_name='group_name',
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80, verbose_name='User status')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='groups.groups')),
            ],
        ),
    ]
