# Generated by Django 3.1.5 on 2021-02-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210201_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='groups.groups'),
        ),
    ]
