# Generated by Django 3.1.6 on 2021-02-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20210203_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='author_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткая биография'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='author_name',
            field=models.CharField(max_length=50, verbose_name='Имя автора'),
        ),
    ]
