# Generated by Django 3.1.6 on 2021-02-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20210203_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='genres_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
