# Generated by Django 3.1.6 on 2021-02-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_genres_genres_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing_house',
            name='publishing_house_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='series',
            name='series_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
