# Generated by Django 3.1.6 on 2021-03-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20210220_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, verbose_name='Название')),
                ('book_desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('book_add', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('book_auth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.authors', verbose_name='Автор')),
                ('book_genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.genres', verbose_name='Жанр')),
                ('book_ph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='groups.publishing_house', verbose_name='Издательство')),
                ('book_sery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='groups.series', verbose_name='Серия')),
            ],
        ),
    ]
