# Generated by Django 3.1.6 on 2021-03-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_book_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='picture',
            new_name='book_img',
        ),
    ]
