# Generated by Django 3.1.6 on 2021-03-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_auto_20210320_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
