# Generated by Django 3.1.6 on 2021-03-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_authors_book_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='book_img',
            new_name='author_img',
        ),
    ]
